version: '3'
volumes:
  data_volume:
services: 
  db: 
    image: postgres:9.6
    environment: 
      POSTGRES_PASSWORD: p@ssw0rd
    volumes:
      # Data volumes
      - data_volume:/var/lib/postgresql/data
      # Scripts
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  adminer:
    image: adminer
    ports:
      - 8081:8080
  frontend:
    image: nginx:1.13
    volumes:
      # Site
      - ./web:/usr/share/nginx/html/
    ports:
      - 81:80
  app:
    image: python:3.6
    volumes:
      # Aplication
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh
    ports:
      - 8080:8080
    
    